### ISSUE TITLE
I get this error, can you tell me why?

### ISSUE THREAD

**Issue by anhky** [Muntasir13/Face-Spoofing-Detection-using-Depth-Wise-Convolution#1]
![image](https://user-images.githubusercontent.com/44550009/126860656-6fc7a7a5-8212-432b-86d3-c241aa326452.png)

**Comment by Muntasir13** [comment]
It seems you are trying to load the model to CPU, which was trained on CUDA. This error is precisely because of that. In order to solve the issue, you may go to the liveness_demo.py file and add map_location=torch.device('cpu') after the os.path.join. Bear in mind, the model may show slower inference as the model would then be loaded in CPU.

**Comment by anhky** [comment]
> It seems you are trying to load the model to CPU, which was trained on CUDA. This error is precisely because of that. In order to solve the issue, you may go to the liveness_demo.py file and add map_location=torch.device('cpu') after the os.path.join. Bear in mind, the model may show slower inference as the model would then be loaded in CPU.

**Comment by anhky** [comment]
Thanks. I was able to run it.
